# Generated by Django 3.2.6 on 2021-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednotes',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
