# Generated by Django 3.2.6 on 2021-08-15 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sharednotes_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('modified_at',)},
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
